measurement_config:
    module: stdout_measurement_logger
    class_name: STDOUTMeasurementLogger
    kwargs:
        measurement_db_name: "link_estimator"
        measurement_definitions:
            UDP_rxstats: "timestamp:double numRx:int32 numTx:int32 numTxLoss:int32 packetDeliveryRatio:double"
            UDP_stats: "numRx:int32 numRxLoss:int32 numTx:int32 numTxLoss:int32"
