## WiSHFUL Handover Controller

controller_info:
  name: 'handover_controller'
  info: 'handover_controller_info'


global_upis:
  handover_module:
      import_as: handover
      module : wishful_wifi_handover
      class_name : WiFiHandover