## WiSHFUL Agent config file

agent_info:
  name: 'wishful_simple_agent_123'
  info: 'wishful_simple_agent_info'

inproc_modules:
  ath9k_module_inproc:
      module : wishful_module_simple
      class_name : SimpleModule
      message_type : [radio, all]

  iperf_module_inproc:
      module : wishful_iperf_driver
      class_name : IperfModule
      message_type : [net, all]

modules:
  discovery_module:
      path : ../../agent_modules/discovery/bin/simple_discovery
      args : ['-d tcp://127.0.0.1:8989', '-u tcp://127.0.0.1:8990']
      message_type : [DiscoverySuccessMsg, DiscoveryRestartMsg]

  synchronization_module:
      path : ../../agent_modules/ptp/bin/ptp_client.py
      args : ['-i eth0']
      message_type : []