## WiSHFUL Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'lo'

modules:
  discovery:
      module : wishful_module_static_discovery
      class_name : StaticDiscoveryModule

  simple:
      module : wishful_module_simple
      class_name : SimpleModule2
      interfaces : ['wlan0', 'wlan1']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule