## WiSHFUL Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'lo'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"wishful_1234"}

  simple:
      module : wishful_module_spectral_scan_ath9k
      class_name : SpectralScanAth9kModule
      interfaces : ['wlan0', 'wlan1']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule