## WiSHFUL Agent config file

agent_info:
  name: 'UWB'
  info: 'Ultra-Wide Band node'
  iface: 'lo'

modules:
  discovery:
    module : wishful_module_discovery_pyre
    class_name : PyreDiscoveryAgentModule
    kwargs: {"iface":"lo", "groupName":"wishful_1234"}

  simple:
    module : wishful_module_uwb
    class_name : UwbModule
    interfaces : ['uwb']
    kwargs: {"dev":"/dev/ttyUSB2"}
