## WiSHFUL Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'lo'

modules:
  wifi_ath:
      module : wishful_module_wifi_ath
      class_name : Ath9kModule
      interfaces : ['ap1']