## WiSHFUL Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'lo'

modules:
  wlan:
      module : wishful_module_wifi
      class_name : WifiModule
      interfaces : ['ap1-wlan0']

  network:
      module : wishful_module_net_linux
      class_name : NetworkModule
