## WiSHFUL Agent config file

agent_info:
  name: 'agent'
  info: 'for IEEE 802.11 linux'
  iface: 'eth0'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"ap1-eth1", "groupName":"wishful_1234"}

  wifi:
      module : wishful_module_wifi_ath
      class_name : Ath9kModule
      interfaces : ['wifi0', 'mon0']
