## WiSHFUL Agent config file

agent_info:
  name: 'wishful_handover_agent'
  info: 'Soft/Hard HO for IEEE 802.11 infrastructure-initiated HO'
  iface: 'eth0'

modules:
  discovery:
      module : wishful_module_static_discovery
      class_name : StaticDiscoveryModule
      kwargs: {"downlink":"tcp://127.0.0.1:8989", "uplink":"tcp://127.0.0.1:8990"}

  simple:
      module : wishful_module_wifi_ath
      class_name : Ath9kModule
      interfaces : ['ap1' 'inject1']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule