## WiSHFUL Agent config file

agent_info:
  name: 'wishful_handover_agent'
  info: 'Soft/Hard HO for IEEE 802.11 infrastructure-initiated HO'
  ip: '192.168.10.10'
  iface: 'eth0'

system_modules:
  discovery:
      path : ../../agent_modules/discovery/bin/simple_discovery
      args : ['-d tcp://127.0.0.1:8989', '-u tcp://127.0.0.1:8990']

  synchronization:
      path : ../../agent_modules/ptp/bin/ptp_client.py
      args : ['-i eth0']

upi_modules:
  simple:
      module : wishful_ath9k_driver
      class_name : Ath9kDriver
      interfaces : [wlan0, wlan1]

  iperf:
      module : wishful_iperf_driver
      class_name : IperfModule