## WiSHFUL Agent config file

agent_info:
  name: 'wishful_handover_agent'
  info: 'Soft/Hard HO for IEEE 802.11 infrastructure-initiated HO'
  iface: 'eth0'

modules:
  discovery:
      module : wishful_module_static_discovery
      class_name : StaticDiscoveryModule

  simple:
      module : wishful_ath9k_driver
      class_name : Ath9kDriver
      interfaces : ['ap1' 'inject1']

  iperf:
      module : wishful_iperf_driver
      class_name : IperfModule