## WiSHFUL Agent config file

agent_info:
  name: 'agent_1'
  info: 'wishful_simple_agent_info'
  iface: 'eth0'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"wishful_1234"}

  wifi:
      module : wishful_module_wifi_ath
      class_name : Ath9kModule
      interfaces : ['ap1' 'inject1']
