## WiSHFUL Controller's config file

controller:
    name: "controller"
    info: "Learning wireless topology"
    dl: "tcp://127.0.0.1:8990"
    ul: "tcp://127.0.0.1:8989"

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryControllerModule
        kwargs: {"iface":"eth0", "groupName":"wishful_1234", "downlink":"tcp://20.0.0.2:8990", "uplink":"tcp://20.0.0.2:8989"}