## WiSHFUL Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'lo'

modules:
  simple:
      module : wishful_module_simple
      class_name : SimpleModule2
      interfaces : ['wlan0', 'wlan1']

  rule_manager:
      module : wishful_module_rules
      class_name : RuleManagerModule

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule