## WiSHFUL Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'lo'

controllers:
  myController:
      module : simple_controller
      class_name : MyController
      kwargs : {"arg": 1}

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"wishful_1234"}

  simple:
      module : wishful_module_simple
      class_name : SimpleModule2
      devices : ['phy0']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule
