## WiSHFUL Agent config file

agent_info:
  name: 'lora_1'
  info: 'lora'
  iface: 'lo'

modules:
  discovery:
    module : wishful_module_discovery_pyre
    class_name : PyreDiscoveryAgentModule
    kwargs: {"iface":"lo", "groupName":"wishful_1234"}

  simple:
    module : wishful_module_lora
    class_name : LoraModule
    interfaces : ['lora']
    kwargs: {"dev": "/dev/ttyUSB0"}
