## WiSHFUL Agent config file

agent_info:
  name: 'agent_topology'
  info: 'Learning wireless topology'
  iface: 'lo'

modules:
  discovery:
      module : wishful_module_static_discovery
      class_name : StaticDiscoveryModule
      kwargs: {"downlink":"tcp://127.0.0.1:8989", "uplink":"tcp://127.0.0.1:8990"}

  wifi:
      module : wishful_module_wifi_ath
      class_name : Ath9kModule
      interfaces : ['wifi0', 'mon0']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule