## WiSHFUL Agent config file

agent_config:
  name: 'local_AP_control_progs'
  info: 'Local WiFi agent'
  type: 'slave'
  iface: 'lo'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"wishful_1234"}

  wlan:
      module : wishful_module_wifi
      class_name : WifiModule
      interfaces : ['phy0']

  netlinux:
      module : wishful_module_net_linux
      class_name : NetworkModule