## WiSHFUL Agent config file

agent_info:
  name: 'agent'
  info: 'for IEEE 802.11 linux'
  iface: 'eth0'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"wishful_1234"}

  rule_manager:
      module : wishful_module_rules
      class_name : RuleManagerModule

  wifi:
      module : wishful_module_wifi_ath
      class_name : Ath9kModule
      interfaces : ['wlan0', 'wlan1']
