measurement_config:
    module: oml_measurement_logger
    class_name: OmlMeasurementLogger
    kwargs:
        measurement_db_name: "link_estimator"
        measurement_definitions:
            UDP_rxstats: "timestamp:double numRx:int32 numTx:int32 numTxLoss:int32 packetDeliveryRatio:double"
        facility: "portable"
