## WiSHFUL local controller config file

agent_info:
  name: 'local controller'
  info: 'for IEEE 802.11 linux'
  iface: 'lo'

modules:
  network:
      module : wishful_module_net_linux
      class_name : NetworkModule

  wifi:
      module : wishful_module_wifi
      class_name : WifiModule
      interfaces : ['wlan0', 'wlan1']