## WiSHFUL Agent config file

agent_info:
  name: 'agent_1'
  info: 'wishful_simple_agent_info'
  iface: 'eth0'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"wishful_1234"}

  rule_manager:
      module : wishful_module_rules
      class_name : RuleManagerModule

  wifi:
      module : wishful_module_simple
      class_name : SimpleModule2
      interfaces : ['wlan0', 'wlan1']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule