## WiSHFUL Agent config file

agent_config:
  name: 'AP1'
  info: 'config for agent running on AP'
  type: 'slave'
  iface: 'ap1-eth1'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"ap1-eth1", "groupName":"wishful_1234"}

  wlan:
      module : wishful_module_wifi
      class_name : WifiModule
      interfaces : ['ap1-wlan0', 'wlan0', 'wlan1']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule
