## WiSHFUL Agent config file

agent_info:
  name: 'wishful_simple_agent_123'
  info: 'wishful_simple_agent_info'
  iface: 'eth0'

system_modules:
  discovery:
      path : ../../agent_modules/discovery/bin/simple_discovery
      args : ['-d tcp://127.0.0.1:8989', '-u tcp://127.0.0.1:8990']

  synchronization:
      path : ../../agent_modules/ptp/bin/ptp_client.py
      args : ['-i eth0']

upi_modules:
  simple:
      module : wishful_module_simple
      class_name : SimpleModule2
      interfaces : [wlan0, wlan1]

  iperf:
      module : wishful_iperf_driver
      class_name : IperfModule