## WiSHFUL Agent config file

agent_info:
    name: 'upi_executor_agent'
    info: 'Contiki upi executor agent'
    iface: 'lo'

modules:
    # discovery:
    #     module : wishful_module_discovery_pyre
    #     class_name : PyreDiscoveryAgentModule
    #     kwargs: {"iface":lo, "groupName":"wishful_ewine"}
    discovery:
        module : wishful_module_static_discovery
        class_name : StaticDiscoveryModule
        kwargs: {"downlink":"tcp://127.0.0.1:8990", "uplink":"tcp://127.0.0.1:8989"}
    gitar_engine:
        module : wishful_module_gitar
        class_name : GitarEngine
        interfaces : ['lowpan0']
        kwargs : {'GitarConfig' : './examples/ewine/gitar.ini','SupportedInterfaces' : ['lowpan0'],'ControlExtensions' : {'taisc' : './examples/ewine/taisc_control_extensions.csv', 'rime' : './examples/ewine/rime_control_extensions.csv'}}
    taisc_connector:
        module : wishful_module_taisc
        class_name : TAISCConnector
        interfaces : ['lowpan0']
        kwargs : {'RadioPrograms' : {"CSMA":0,"TDMA":2,"TSCH":1}}
    rime_connector:
        module : wishful_module_rime
        class_name : RIMEConnector
        interfaces : ['lowpan0']
