## WiSHFUL Agent config file

agent_info:
  name: 'agent_2'
  info: 'agent_info'
  iface: 'ap2-eth1'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"ap2-eth1", "groupName":"wishful_1234"}

  simple:
      module : wishful_module_simple
      class_name : SimpleModule2
      interfaces : ['wlan0', 'wlan1']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule
